apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: observability
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: observability
type: Opaque
stringData:
  POSTGRES_URL: "postgresql://postgres:postgres123@postgres-service.observability.svc.cluster.local:5432/postgres"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediation-agent
  namespace: observability
---
# Role in default namespace (scoped). If you want multiple namespaces, create one role per namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remediation-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get","list","watch","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remediation-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: remediation-agent
    namespace: observability
roleRef:
  kind: Role
  name: remediation-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-agent
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remediation-agent
  template:
    metadata:
      labels:
        app: remediation-agent
    spec:
      serviceAccountName: remediation-agent
      containers:
        - name: remediation-agent
          image: sreedocker123/remediation-agent:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_URL
            - name: MINIO_ENDPOINT
              value: "http://minio.observability.svc.cluster.local:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_SECRET_KEY
            - name: MINIO_BUCKET
              value: "remediation-logs"
            - name: ALLOWED_OPS
              value: "describe,get,delete,logs,restart"
            - name: ALLOWED_KINDS
              value: "pod,deployment,configmap,hpa"
            - name: ALLOWED_NAMESPACES
              value: "default,observability,monitoring"
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: remediation-agent
  namespace: observability
spec:
  type: NodePort
  selector:
    app: remediation-agent
  ports:
  - name: http
    port: 8002
    targetPort: 8002
    nodePort: 30082


