# loki-pv-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
spec:
  storageClassName: loki-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/loki   # path on your node(s)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: monitoring
spec:
  storageClassName: loki-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

