apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m

    route:
      receiver: "default"
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - match:
            alertname: "PodImagePullError"
          receiver: "alert-agent"
        - match:
            severity: "critical"
          receiver: "discord"

    receivers:
      - name: "default"
        webhook_configs:
          - url: "http://alert-agent.observability.svc.cluster.local:8000/alert"
            send_resolved: true

      - name: "alert-agent"
        webhook_configs:
          - url: "http://alert-agent.observability.svc.cluster.local:8000/alert"
            send_resolved: true

      - name: "discord"
        webhook_configs:
          - url: "https://discord.com/api/webhooks/123456789012345678/abcdefghijklmnopqrstuvwxyz"
            send_resolved: true

    inhibit_rules:
      - source_match:
          severity: "critical"
        target_match:
          severity: "warning"
        equal: ["alertname", "namespace"]

