# =========================
# 3️⃣ ServiceAccount
# =========================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
  namespace: observability

---

# =========================
# 4️⃣ ClusterRole
# =========================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]

---

# =========================
# 5️⃣ ClusterRoleBinding
# =========================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector
subjects:
  - kind: ServiceAccount
    name: vector
    namespace: observability
roleRef:
  kind: ClusterRole
  name: vector
  apiGroup: rbac.authorization.k8s.io

---
